/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.26.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import { CosmWasmClient } from "@cosmjs/cosmwasm-stargate";
import {
  BigNumberBytes,
  WMap,
  PointG1Bytes,
  PointG2Bytes,
  PointG1Bytes1,
  PointG1Bytes2,
  PointG1Bytes3,
  PointG1Bytes4,
  PointG2Bytes1,
  PointG1Bytes5,
  PointG1Bytes6,
  PointG2Bytes2,
  PointG2Bytes3,
  InstantiateMsg,
  WCredentialPubKey,
  WCredentialPrimaryPubKey,
  WCredentialRevocationPubKey,
  ExecuteMsg,
  QueryMsg,
} from "./IdentityPlugin.types";
export interface IdentityPluginReadOnlyInterface {
  contractAddress: string;
}
export class IdentityPluginQueryClient
  implements IdentityPluginReadOnlyInterface
{
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
  }
}
